### ISSUE TITLE
Getting KeyError while calling get_email_address

### ISSUE THREAD

**Issue by Kh4lidMD** [Temp-Mail-API/Python#3]
When I call 

```py
from tempmail import TempMail

tm = TempMail()
email = tm.get_email_address()
```
I get
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\..\AppData\Local\Programs\Python\Python310\lib\site-packages\tempmail.py", line 68, in get_email_address
    self.domain = random.choice(available_domains)
  File "C:\Users\..\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
KeyError: 4
```

**Comment by tyo8** [comment]
I'm having this issue as well:
```
email = tm.get_email_address()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tyo/miniconda3/lib/python3.10/site-packages/tempmail.py", line 68, in get_email_address
    self.domain = random.choice(available_domains)
  File "/home/tyo/miniconda3/lib/python3.10/random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
KeyError: 2
```
is `available_domains` empty?
